# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c16b25efb9aa29a80ea92d67ba14ca761f6e5dc149f021d3c2a7cfa23190e4643d8c0bf2ea9fe6834101e02c25a37c39f7894c51f3238149a3dac5b5eaa0655

test:
  secret_key_base: 6e96b052eebac88ee64d92f36ec3bf0fee4dda0904a54adb7d2a661069d3635e331f37c5f7505147210ef9b384d2bc3ae9b91b52a0f73c8afe4074f041a5548a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
