version: '3'
services:

  frontend:
    build: ./frontend
    container_name: rails_react_app_frontend
    command: npm run start
    ports:
      - '8080:80'
    volumes:
     - ./frontend:/app
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    container_name: rails_react_app_backend
    command: rails s -b 0.0.0.0 -p 3050
    ports:
      - '3050:3050'
    depends_on:
      - db
      - frontend
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
      - db_data:/var/lib/postgresql/data
    environment:
      RAILS_ENV: development
    tty: true
    stdin_open: true

  db:
    image: postgres:10.1
    container_name: rails_react_app_db
    ports:
      - '5432'

volumes:
  db_data:
  bundle:
